<?xml version="1.0" encoding="UTF-8"?>

  <!-- ******************************************************************
	*
	* Version 1.0 	SMF-Format.xsd
	*
	* © 2025 Steve Hanson <smhdfdl@gmail.com>
	*
	* This DFDL schema provides a set of DFDL property values and other DFDL constructs 
	* to assist in the creation of DFDL schemas that model z/OS SMF binary records.
	* 
	* Example use: 
	* 
	*      <xsd:import namespace="http://www.ibm.com/dfdl/SMFFormat" schemaLocation="SMF-Format.xsd"/>
	******************************************************************* -->

<xsd:schema targetNamespace="http://www.ibm.com/dfdl/SMFFormat"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:dfdl="http://www.ogf.org/dfdl/dfdl-1.0/"
	xmlns:fn="http://www.w3.org/2005/xpath-functions"
	xmlns:tns="http://www.ibm.com/dfdl/SMFFormat">
	<xsd:annotation>
		<xsd:appinfo source="http://www.ogf.org/dfdl/">
			
			<dfdl:defineFormat name="SMFFormat">
				<dfdl:format encoding="037" ignoreCase="no" byteOrder="bigEndian"
					lengthUnits="bytes" prefixIncludesPrefixLength="no" representation="binary" 
					textPadKind="padChar" textTrimKind="padChar" textStringJustification="left" truncateSpecifiedLengthString="yes"
					decimalSigned="yes" textNumberCheckPolicy="lax"
					textNumberJustification="right" textBooleanJustification="left" 
					sequenceKind="ordered" choiceLengthKind="implicit" separator="" 
					documentFinalTerminatorCanBeMissing="no" lengthKind="explicit"
					textNumberRounding="pattern" textStandardBase="10" textStandardDecimalSeparator="."
					textStandardExponentCharacter="E" escapeSchemeRef=""
					alignment="1" alignmentUnits="bytes" leadingSkip="0" trailingSkip="0"
					fillByte="0" textStringPadCharacter="%SP;" initiatedContent="no"
					textNumberPadCharacter="%SP;" textBooleanPadCharacter="%SP;"
					textNumberRep="zoned" textNumberRoundingMode="roundUp"
					calendarPatternKind="explicit" calendarPattern="01yyDDD"
					calendarCheckPolicy="lax" calendarTimeZone="UTC"
					calendarObserveDST="yes" calendarFirstDayOfWeek="Monday"
					calendarDaysInFirstWeek="4" textCalendarJustification="left"
					textCalendarPadCharacter="%SP;" calendarCenturyStart="53"
					calendarLanguage="en-US" occursCountKind="fixed"
					textStandardInfinityRep="Inf" textStandardNaNRep="NaN"
					textBooleanTrueRep="true" textBooleanFalseRep="false"
					initiator="" terminator="" outputNewLine="%CR;%LF;"
					nilKind="literalValue" useNilForDefault="no" nilValueDelimiterPolicy="none"
					binaryNumberRep="binary" binaryPackedSignCodes="C D F C"
					binaryDecimalVirtualPoint="0" binaryNumberCheckPolicy="lax"
					binaryCalendarRep="packed"  binaryBooleanTrueRep="1"  binaryBooleanFalseRep="0"
					binaryFloatRep="ieee" textBidi="no" emptyValueDelimiterPolicy="none" floating="no" >
				</dfdl:format>
			</dfdl:defineFormat>
			
			
		</xsd:appinfo>
	</xsd:annotation>
</xsd:schema>
